### ISSUE TITLE
question regarding backwards compatibility

### ISSUE THREAD

**Issue by johnneman** [rsyslog/rsyslog-pkg-rhel-centos#112]
Guten Tag!

I currently have multiple servers with rsyslog versions as listed below;
- version 8.2004.0 from 2020-04-28
- version 8.24.0 from 2017-01-10

I would like to upgrade these servers to the latest version. Should I be worried about compaibility? Other rsyslog clients with numerous different versions are talking to those servers..

I'm not sure how to see what versions the clients are using. Is there a way to see this in the rsyslog server logging?

Thank you very much for your reply!

Best regards,

John Brummer

PS: I also see small error.. When I'm on https://www.rsyslog.com/plugins/ and follow the link for jsonparse it shows 'Invalid file specified'.. I'm curious to the json capabilities :)

**Comment by davidelang** [comment]
I can't say that there are never any backwards compatibility issues, but we do 
try very hard to avoid them (and almost always consider them bugs to be fixed), 
and from 8.24 and 8.2004 the only thing I can think of are some odd TLS cases 
(anon authentication and one other that was worked in the last couple of weeks, 
I don't know if that got in to 8.2206 or not)

the only way to tell the client versions is if the clients send their internal 
logs to the remote server, it's not something that exists in each message sent. 
The startup messages are especially useful, but if you look for $programname 
startswith("rsyslog") you should find what you are looking for.

David Lang

**Comment by johnneman** [comment]
Thanks for replying :)
