### ISSUE TITLE
Harmonise postrotate script in logrotate config with stock el packages

### ISSUE THREAD

**Issue by qha** [rsyslog/rsyslog-pkg-rhel-centos#123]
On el8 and el9 the postrotate script in logrotate config seem to be pretty much equivalent to that shipped with the stock (rh)el packages. They are not identical however which will keep sharedscripts from merging them with other postrotate scripts that try to harmonise with the stock packages.

(We try to do this for a /var/log/debug that we added to our rsyslog config.)

The differences are:
`systemctl kill -s HUP rsyslog.service` in the Adiscon packages vs:
`/usr/bin/systemctl kill -s HUP rsyslog.service >/dev/null 2>&1 || true` in the stock packages.

**Comment by qha** [comment]
(On el7 i presume #42 makes this a nonstarter.)

**Comment by rgerhards** [comment]
@alorbach sounds good to me, what do you think?

**Comment by alorbach** [comment]
We can adapt the changes from the stock packages, they look reasonable to me.
