### ISSUE TITLE
"http://rpms.adiscon.com/v8-stable-daily/rsyslog-daily.repo" is not available

### ISSUE THREAD

**Issue by wanghaopu** [rsyslog/rsyslog-pkg-rhel-centos#139]
We want to use daily stable build following [the instruction](https://www.rsyslog.com/rhelcentos-rpms/) but find that file is not available.

**Comment by rgerhards** [comment]
I can access both files. Please post the output of `wget`.

**Comment by wanghaopu** [comment]
Thanks for looking at this. Below is the output of `wget`.

(base) [whp@ip1 ~]$ wget http://rpms.adiscon.com/v8-stable-daily/rsyslog-daily.repo
--2023-12-05 09:07:28--  http://rpms.adiscon.com/v8-stable-daily/rsyslog-daily.repo
Resolving rpms.adiscon.com (rpms.adiscon.com)... 45.55.202.239
Connecting to rpms.adiscon.com (rpms.adiscon.com)|45.55.202.239|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-12-05 09:07:28 ERROR 404: Not Found.
