### ISSUE TITLE
Fix source reference in libgt.spec

### ISSUE THREAD

**Issue by portante** [rsyslog/rsyslog-pkg-rhel-centos#16]
The source tar ball reference in the libgt file seems to say it can be found at: `http://libgt.adiscon.com/files/download/libgt-0.3.11.tar.gz`

However, the name `libgt.adiscon.com` does not appear to resolve.

**Comment by alorbach** [comment]
Looks like a copy & paste bug, source should be this instead: 
https://github.com/rsyslog/libgt/archive/master.zip
 Will be fixed

**Comment by friedl** [comment]
Changed the spec file to reference the source found on Github.
