### ISSUE TITLE
libksi: problems due to version incompatibilities

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog-pkg-rhel-centos#18]
libksi introduced an incompatbile API with its newest version, which is required in order to use the new rsyslog code. While we have built a new package, there are file name conflicts, which lead to install failures if both old and new versions are to be installed. However, we cannot remove the old version, as this would render defective existing rsyslog versions. So this is not easy to settle.

A work-around proposal is to create a new rsyslog-ksi subpackage (and move those component over from the core package). In those cases, there seem to be relaxed check on file name conflicts so that we could work around the issues in a sufficiently reliable way.

**Comment by portante** [comment]
Would this help?  It works like a champ.

https://karloluiten.nl/rhel-replace-rsyslog-with-rsyslog7-without-clearing-dependencies/

**Comment by alorbach** [comment]
Not sure how this can help us with the current problem. 

When I try to update the libksi package, this will fail as yum won't be able to remove libksi. libksi.0.0.0 still needed by current installed rsyslog package but libksi.1.0.0 is to be installed by the new package. 

When I try to duplicate the package from libksi to libksi1, I get conflicts with the same filesnames between both packages. Yet I can't remove libksi before as rsyslog base package still needs it. 

I see no other way then getting the components that use libksi out of the rsyslog base package, so that we can update libksi package without getting dependency trouble of the base rsyslog package. 

If there is another way, please let me know ... this is really giving me headaches ;)

**Comment by portante** [comment]
I believe the above solves that: you use yum shell to say you want to remove one, and add another, it figures out the dependencies and ensures it only replaces what is necessary.  So I think you create a new rsyslog that depends on the new libksi, and you remove the two old ones and install the two new ones via yum shell, and nothing other than those two packages is removed.

**Comment by alorbach** [comment]
Ok but if I understand this right, this would mean that every user which has rsyslog package installed would have to do this in order to update rsyslog?

**Comment by portante** [comment]
Yes, I think so.  Is libksi in the same package as the base syslog?  Or is it an rsyslog-libksi separate package?

**Comment by rgerhards** [comment]
libksi is a third-party component (https://github.com/GuardTime/libksi), for which we provide a convenience package because nobody else does. 

The rsyslog KSI signing modules are currently inside the base package. IMHO it would be a good idea in any case to make them their own rsyslog-component (which then depends on libksi) because not everyone needs that functionality.

**Comment by alorbach** [comment]
Currently the ksi depending components are in the rsyslog base package. 
I aggree to Rainer, I also want to do is to split them into their own rsyslog-ksi package. Users needing it can install it (including the libksi dependency).

**Comment by alorbach** [comment]
lmsig_ksi.so is now in rsyslog-ksi. 
rscryutil and rsgtutil is now in rsyslog-utils as they also add dependency to libksi.

This solves the update dependency problem.

**Comment by rgerhards** [comment]
rscryutil is **not** related to KSI. It is the user tool that is needed if log file encryption is enabled. So it does not belong into rsyslog-ksi.

**Comment by alorbach** [comment]
rscryutil and rsgtutil are now in rsyslog-utils

**Comment by alorbach** [comment]
Alternative we can leave rscryutil in the base package and put rsgtutil into rsyslog-ksi?

**Comment by rgerhards** [comment]
That's the way to go. As I said, rscyrutil has no relationship to KSI and needs to be together with the rest of the encryption components.

**Comment by alorbach** [comment]
Done, the issue can be closed then.
