### ISSUE TITLE
Packages for EL5 of rsyslog >8.16.0-1 not available

### ISSUE THREAD

**Issue by lammel** [rsyslog/rsyslog-pkg-rhel-centos#24]
Freshly installing rsyslog for CentOS 5.x (RHEL5) showed that the latest package version in the repository for EL5 is 8.16.0-1 built in 26th Jan 2016. Also other addon packages (e.g. rsyslog-relp, rsyslog-pgsql, ...) are not built for later versions.

See http://rpms.adiscon.com/v8-stable/epel-5/x86_64/RPMS/
- Latest: rsyslog-8.16.0-1.el5.centos.x86_64.rpm    2016-01-26 14:04    792K  

The other RHEL/CentOS repositories for EL6 and EL7 do show builds up to the latest rsyslog-8.18.0-1 (with multiple other package version between 8.16.0-1 and rsyslog-8.18.0-1
- Latest: rsyslog-8.18.0-1.el7.x86_64.rpm   2016-04-19 09:23    635K  

Is there any specific reason this version is used? 
Or might the build be failing for some reason?

I do hope that this can be easily fixed. Looking forward to the lastest packages for EL5 ;-)

**Comment by friedl** [comment]
RHEL5 is EOL
