### ISSUE TITLE
Rsyslog 8.20.0-1 packages not published

### ISSUE THREAD

**Issue by qha** [rsyslog/rsyslog-pkg-rhel-centos#27]
Hi!

Rsyslog 8.20.0 has been out since 2016-07-12 and the spec file in this repository appears to build rpms of Rsyslog 8.20.0-1 but no such rpms are available on http://rpms.adiscon.com/v8-stable/ yet.

Is there any particular reason for this?

Best regards
/Ulrik Haugen

**Comment by friedl** [comment]
Hi Ulrik,

we are still experimenting with the current packages, since we had some trouble with the latest release. 

We hope to be able to provide functional packages for the current version soon.

Florian

**Comment by qha** [comment]
Ok, thank you for your very prompt response!
