### ISSUE TITLE
rsyslogd 8.27.0 could not load module '/lib64/rsyslog/mmnormalize.so' because liblognorm5 was not upgraded.

### ISSUE THREAD

**Issue by jay7x** [rsyslog/rsyslog-pkg-rhel-centos#34]
I've updated some servers to rsyslog v8.27.0 today and found following problem:

```
# rsyslogd -N 1
rsyslogd: version 8.27.0, config validation run (level 1), master config /etc/rsyslog.conf
rsyslogd: could not load module '/lib64/rsyslog/mmnormalize.so', dlopen: /lib64/rsyslog/mmnormalize.so: undefined symbol: ln_loadSamplesFromString  [v8.27.0 try http://www.rsyslog.com/e/2066 ]
```

It seems `liblognorm5-2.0.3` is required now for rsyslog v8.27 but version is not specified in dependencies. So it's not updated along with `rsyslog-mmnormalize` module.

```
# rpm -qR rsyslog-mmnormalize
libc.so.6()(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libfastjson.so.4()(64bit)
liblognorm.so.5()(64bit)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rsyslog = 8.27.0-1.el7
rtld(GNU_HASH)
rpmlib(PayloadIsXz) <= 5.2-1
```

**Comment by friedl** [comment]
I just set the dependency accordingly in the spec file and re-built the packages. can you please try again installing this?

**Comment by jay7x** [comment]
I've just tried and see no changes:

```
# rpm -qa rsyslog-mmnormalize
rsyslog-mmnormalize-8.27.0-2.el7.x86_64
# rpm -qR rsyslog-mmnormalize
libc.so.6()(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libfastjson.so.4()(64bit)
liblognorm.so.5()(64bit)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rsyslog = 8.27.0-2.el7
rtld(GNU_HASH)
rpmlib(PayloadIsXz) <= 5.2-1
# rpm -qa liblognorm5
liblognorm5-2.0.2-1.el7.x86_64
```

So `liblognorm5` was not upgraded as dependency of `rsyslog-mmnormalize`.

**Comment by jay7x** [comment]
I had quick look on spec files. It seems you've specified `liblognorm5` version for `BuildRequires` but not for runtime `Requires`. Could you try like it done for `relp` module? ```(Requires: librelp >= 1.2.10)```

**Comment by friedl** [comment]
Should be fixed by setting Requires to liblognorm5.
