### ISSUE TITLE
Error on installing/updating rsyslog-8.27.0-3.el7.x86_64.rpm

### ISSUE THREAD

**Issue by thunder-spb** [rsyslog/rsyslog-pkg-rhel-centos#36]
Hi guys,

Looks like today's release is not working:
```sh
    ---> Package rsyslog.x86_64 0:8.27.0-3.el7 will be an update
    --> Processing Dependency: libksi.so.7()(64bit) for package: rsyslog-8.27.0-3.el7.x86_64
    --> Finished Dependency Resolution
    Error: Package: rsyslog-8.27.0-3.el7.x86_64 (rsyslog)
               Requires: libksi.so.7()(64bit)
     You could try using --skip-broken to work around the problem
     You could try running: rpm -Va --nofiles --nodigest
```
Version 8.27.0-**2** works fine.

I'm using CentOS Linux release 7.2.1511 (Core)

Thanks,

**Comment by friedl** [comment]
Hi,

sorry for the inconvenience. There snuck an error into the newest package build. The libksi requirement should not be needed for the rsyslog base RPM.

We reverted the online library back to the previous version, so the latest version is 8.27.0-2. This will not have the unnecessary libksi requirement.

Please note, for yum to properly register the correct RPM, you might need to clean the yum cache first before installing/updating rsyslog.

Again, sorry for the inconvenience.

Florian

**Comment by thunder-spb** [comment]
Thank you Florian.
