### ISSUE TITLE
Bug: CentOS package: logrotate setting

### ISSUE THREAD

**Issue by schlitzered** [rsyslog/rsyslog-pkg-rhel-centos#37]
at least the CentOS 7 package delivers a logrotate setting with the file "/etc/logrotate.d/syslog", with the content:

/var/log/cron
/var/log/maillog
/var/log/messages
/var/log/secure
/var/log/spooler
{
    sharedscripts
    postrotate
        /bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
    endscript
}

but kill -HUP will not work, because the pidfile is '/var/run/rsyslogd.pid' not 'cat /var/run/syslogd.pid'

could you please fix this?

**Comment by shane-lawrence** [comment]
This is a duplicate of #25, and I believe the issue was also discussed in #15.

**Comment by shane-lawrence** [comment]
A fix has been proposed in #30 but it doesn't appear to have been reviewed.

**Comment by schlitzered** [comment]
right, i forgot about it. closing this one

**Comment by arrjay** [comment]
still unmerged, so this is still an _issue_ while not a PR :)
