### ISSUE TITLE
find custom patches

### ISSUE THREAD

**Issue by wdauchy** [rsyslog/rsyslog-pkg-rhel-centos#40]
Hello,

It might be a dumb question but I cannot find the files mentioned as patch in centos7 packages such as:
Patch0: rsyslog-8.24.0-sd-service.patch
Patch1: 01-rsyslog-8.32.0-rscript_parse_json.patch
Patch2: 02-rsyslog-8.32.0-jsonmesg-assert.patch
Patch3: 03-8.32.0-external-cmd-parser.patch

I expected to find them in SOURCES directory but cannot find them. What am I missing here?

Thanks,

**Comment by friedl** [comment]
The patches themself were not uploaded to the project files, because they will be discarded on the next release anyway. This was to not clutter the project files with soon-to-be-unused files.

**Comment by friedl** [comment]
We discussed this internally a little and decided that the patch files should be provided of course. I uploaded them just now and they are available.

Here is the commit:
https://github.com/rsyslog/rsyslog-pkg-rhel-centos/commit/8a78a5fd17115c86542c87763cedc46b5b5422d4

**Comment by wdauchy** [comment]
thanks
