### ISSUE TITLE
rsyslog-8.39.0-2.el7 requires libestr >= 0.1.11

### ISSUE THREAD

**Issue by LTIOfficial** [rsyslog/rsyslog-pkg-rhel-centos#51]
Revealed during the attempt at updating from rsyslog 8.38.0-1.el7 via yum-rsyslog repo in Centos 7:

`rsyslog-8.39.0-2.el7.x86_64 requires libestr >= 0.1.11`

It appears that the most recent libestr available to Centos 7 is 0.1.9-2.el7 in the Base.  Epel does not appear to carry it.

**Comment by friedl** [comment]
libestr 0.1.11 is available on the rsyslog repo, so there should be no problem when installing rsyslog from there anyway.

The official EPEL repo is always behind for a number of releases.

**Comment by LTIOfficial** [comment]
Thanks @friedl.
Interestingly, it didn't pick up libestr until I excluded it from the CentOS 7 Base repo.

For anyone experiencing a similar issue where you have the rsyslog repo installed and enabled:
Edit the CentOS7 Base repo file
`vim /etc/yum.repos.d/CentOS-Base.repo`

to include the following line in each of the repo sections included in it.
```
[base]
...
exclude= rsyslog* libestr*

[updates]
...
exclude= rsyslog* libestr*

etc.
```
