### ISSUE TITLE
Upgrade RedHat Packages

### ISSUE THREAD

**Issue by trumpetcreek** [rsyslog/rsyslog-pkg-rhel-centos#54]
We have been using standard Redhat packages for RHEL 6 and 7 that come with the distribution, but would like to use the latest stable version on a few of our production systems that need more recent features.  

Using the guidance here: https://www.rsyslog.com/rhelcentos-rpms/ it seems pretty straight forward.  How does this work with the standard Redhat repos that rsyslog is normally updated with?  Does it just update against the new adiscon.com repos going forward?  Or do you need to do something on the OS to stop it from trying to update against Redhat?  Just don't want to fight conflicts when we try to update the package in the future.

**Comment by davidelang** [comment]
On Wed, 10 Apr 2019, credog wrote:

> Using the guidance here: https://www.rsyslog.com/rhelcentos-rpms/ it seems 
> pretty straight forward.  How does this work with the standard Redhat repos 
> that rsyslog is normally updated with?  Does it just update against the new 
> adiscon.com repos going forward?  Or do you need to do something on the OS to 
> stop it from trying to update against Redhat?  Just don't want to fight 
> conflicts when we try to update the package in the future.

if you have multiple repos configured, yum will grab the latest version across 
all repos, so the rsyslog based repos will always have a later version, so you 
should have no problems (as long as the packages installed have the same names)

David Lang
