### ISSUE TITLE
RPM Package Signature - Key Verification

### ISSUE THREAD

**Issue by monobaila** [rsyslog/rsyslog-pkg-rhel-centos#55]
I'd like to verify the packages hosted on http://rpms.adiscon.com before installing.

They're signed but the signing key is also hosted on the same domain which is only accessible over HTTP (There is an open issue about this - https://github.com/rsyslog/rsyslog-website/issues/45). I'm struggling to validate the fingerprint  presented to me when I enable gpgcheck -

`
Retrieving key from http://rpms.adiscon.com/RPM-GPG-KEY-Adiscon
Importing GPG key 0xE00B8985:
 Userid     : "Andre Lorbach (RPM Signing Key) <alorbach@adiscon.com>"
 Fingerprint: 712d 4e18 794d c570 e287 0861 e0f2 33b3 e00b 8985
 From       : http://rpms.adiscon.com/RPM-GPG-KEY-Adiscon
Is this ok [y/N]: 
`

Is there another domain accessible via HTTPS where signing key fingerprints are maintained? If not, it would be good to add them to the [instructions](https://www.rsyslog.com/rhelcentos-rpm) to setup the yumrepo.

Thanks!

**Comment by rgerhards** [comment]
Very valid concern, many thanks!

@friedl can you place the key on the CentOS download page on the main site please?

**Comment by friedl** [comment]
Public GPG key added to instructions page.

**Comment by monobaila** [comment]
Thanks for the quick follow up! It might be easier just to upload the fingerprint so people can quickly verify but the whole key also works.
