### ISSUE TITLE
el6 repo is missing rpm for 8.1910

### ISSUE THREAD

**Issue by Nicheurity** [rsyslog/rsyslog-pkg-rhel-centos#62]
el6 repo is missing rpm for 8.1910

http://rpms.adiscon.com/v8-stable/epel-6/x86_64/RPMS/
- Version: 8.1908-02
- Last Modified: 2019-08-27 11:33

http://rpms.adiscon.com/v8-stable/epel-7/x86_64/RPMS/
- Version: 8.1910-01
- Last Modified: 2019-10-01 09:16

Please update the el6 repo with latest release version rsyslog 8.1910

**Comment by friedl** [comment]
Please check again. The EL6 repo should now have the files for 8.1910.0-1.

Sorry for the inconvenience.
