### ISSUE TITLE
Centos rsyslog package does not have the improg module

### ISSUE THREAD

**Issue by alexeevit** [rsyslog/rsyslog-pkg-rhel-centos#85]
Hello,

I found that the centos package does not have the improg module. I found also that fedora has the `rsyslog-extra` package that contains the improg module, but we don't have any opportunity to install improg in centos.

Is there any way to load the module without building the program manually?

**Comment by rgerhards** [comment]
@friedl I would assume that this can easily be packaged. Can you give it a try?

**Comment by friedl** [comment]
@alexeevit I checked on the package and you are right. improg was not included.
I also checked on the CentOS and Fedora packages as to how they are built, so we are doing it in the same way. Since you mentioned rsyslog-extra, I especially looked for that, but couldn't find it. The Fedora package has the improg module in the base package so I opted for the same variant. 

The packages are currently building and will be available very soon. The improg module will, as I said, be available in the base rsyslog package.

**Comment by alexeevit** [comment]
Oh, sorry, I messed fedora with altlinux: https://altlinux.pkgs.org/sisyphus/classic-x86_64/rsyslog-extra-8.2006.0-alt1.x86_64.rpm.html
Fedora has the improg module in the base package indeed.

Thanks for your work!

**Comment by friedl** [comment]
It's in the base package now ;) 
But, since it is not used in the original CentOS package, there shouldn't be any conflict. 

The packages are uploaded, so please give it a try. It would be nice if you could report back if it was a success (or not).

**Comment by alexeevit** [comment]
Hey, thanks for the quick reaction!
I've installed the rsyslog from the nightly repo and it looks like it still doesn't have improg:

```
# ls -1 /usr/lib64/rsyslog
imdiag.so
imfile.so
imjournal.so
imklog.so
immark.so
impstats.so
imptcp.so
imtcp.so
imudp.so
imuxsock.so
lmcry_gcry.so
lmnet.so
lmnetstrms.so
lmnsd_ptcp.so
lmregexp.so
lmtcpclt.so
lmtcpsrv.so
lmzlibw.so
mmanon.so
mmcount.so
mmexternal.so
mmpstrucdata.so
mmsequence.so
mmutf8fix.so
omjournal.so
ommail.so
omprog.so
omruleset.so
omstdout.so
omtesting.so
omuxsock.so
pmaixforwardedfrom.so
pmcisconames.so
pmlastmsg.so
pmnull.so
pmsnare.so
```

```
# rsyslogd
rsyslogd: could not load module 'improg', errors: trying to load module /usr/lib64/rsyslog/improg.so: /usr/lib64/rsyslog/improg.so: cannot open shared object file: No such file or directory [v8.2010.0.master try https://www.rsyslog.com/e/2066 ]
```

**Comment by atc0005** [comment]
> @alexeevit: Hey, thanks for the quick reaction!
> I've installed the rsyslog from the nightly repo and it looks like it still doesn't have improg:

FWIW, the stable version does (CentOS 7 box):

```ShellSession
$ ls -lh /usr/lib64/rsyslog/improg.so
-rwxr-xr-x. 1 root root 20K Sep 15 11:42 /usr/lib64/rsyslog/improg.so

$ rpm -q rsyslog
rsyslog-8.2008.0-2.el7.x86_64
```

Another box of ours that hasn't auto-updated rsyslog yet (RHEL 7) is missing the file:

```ShellSession
$ ls -lh /usr/lib64/rsyslog/improg.so
ls: cannot access /usr/lib64/rsyslog/improg.so: No such file or directory

$ rpm -q rsyslog
rsyslog-8.2008.0-1.el7.x86_64
```

**Comment by alexeevit** [comment]
Yeah, it works ok with the stable version, so we can close the issue, I guess.

Thanks for the help!
